# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

strategy:
  matrix:
    Node8:
      NODEJS_VERSION: '8.x'
    Node9:
      NODEJS_VERSION: '9.x'
    Node10:
      NODEJS_VERSION: '10.x'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm ci
    npx lerna bootstrap
  displayName: 'Install Dependencies'

- script: |
    npx lerna run build
  displayName: 'Run Build Processes'

- script: |
    npx lerna exec -- npm run test-ci
  displayName: 'Run Tests'
